language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - dev

cache:
  directories:
  - $HOME/.gradle

before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/dev
  - git rm --cached --ignore-unmatch index.html
